a = int(input("Enter 1st value: "))
b = int(input("Enter 2nd value: "))
print(a,"+",b,"is: ",a+b)
print(a,"-",b,"is: ",a-b)
print(a,"*",b,"is: ",a*b)
print(a,"/",b,"is: ",a/b)
print(a,"%",b,"is: ",a%b)
print(a,"^",b,"is: ",a^b)
